# Generated by Django 6.0.7 on 2026-07-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='title',
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
